XBotCore:
  config_path: "iit-centauro-ros-pkg/centauro_config/centauro.yaml"

XBotInterface:
  urdf_path: "iit-centauro-ros-pkg/centauro_urdf/urdf/centauro.urdf"
  srdf_path: "iit-centauro-ros-pkg/centauro_srdf/srdf/centauro.srdf"
  joint_map_path: "iit-centauro-ros-pkg/centauro_config/centauro_joint_map.yaml"

RobotInterface:
  framework_name: "ROS"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "true"
  
MasterCommunicationInterface:
  framework_name: "ROS"

XBotRTPlugins:
  plugins: ["HomingExample"]
  io_plugins: []
  
NRTPlugins:
  plugins: []

WebServer:
  enable: "false"
  address: "127.0.0.1"
  port: "8081"

SimulationOptions:
  verbose_mode: "true"

